# Generated by Django 2.0.4 on 2018-04-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action_Type', models.IntegerField(choices=[(1, 'Add'), (2, 'Delete'), (3, 'Change')], default=1)),
                ('Old_version', models.TextField(null=True)),
                ('New_version', models.TextField(null=True)),
                ('Status', models.IntegerField(choices=[(1, 'Approved'), (2, 'New'), (3, 'Changes required'), (4, 'Updated')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Alternative_opinion',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Status', models.IntegerField(choices=[(1, 'Approved'), (2, 'New'), (3, 'Changes required')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePersonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Article_Person_link',
            },
        ),
        migrations.CreateModel(
            name='ArticlePhotoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Article_Photo_link',
            },
        ),
        migrations.CreateModel(
            name='ArticleTermLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Article_Term_link',
            },
        ),
        migrations.CreateModel(
            name='BlockOfText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
            ],
            options={
                'db_table': 'Block_of_text',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subtitle', models.CharField(max_length=50)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Paragraph',
            },
        ),
        migrations.CreateModel(
            name='PersonBriefInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateField()),
                ('Date_of_death', models.DateField()),
                ('Brief_info', models.TextField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Person_brief_info',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.TextField()),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char_number', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Link', models.TextField()),
                ('Date_upload', models.DateField()),
                ('Source_Type', models.IntegerField(choices=[(1, 'Web'), (2, 'TextBook')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=50)),
                ('Definition', models.TextField()),
            ],
            options={
                'db_table': 'Term',
            },
        ),
        migrations.CreateModel(
            name='UdvUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Moderator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='blockoftext',
            name='Paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Paragraph'),
        ),
        migrations.AddField(
            model_name='blockoftext',
            name='Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Source'),
        ),
        migrations.AddField(
            model_name='articletermlink',
            name='Term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Term'),
        ),
        migrations.AddField(
            model_name='articlephotolink',
            name='Photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Photo'),
        ),
        migrations.AddField(
            model_name='articlepersonlink',
            name='Person_brief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.PersonBriefInfo'),
        ),
        migrations.AddField(
            model_name='article',
            name='Moderator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='article',
            name='Parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='server.Article'),
        ),
        migrations.AddField(
            model_name='alternativeopinion',
            name='Block_of_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.BlockOfText'),
        ),
        migrations.AddField(
            model_name='alternativeopinion',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='Block_of_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.BlockOfText'),
        ),
        migrations.AddField(
            model_name='action',
            name='Moderator_dst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='moderator_destination', to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='Moderator_src',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='moderator_source', to='server.UdvUser'),
        ),
    ]
