# Generated by Django 2.0.4 on 2018-04-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Status_Type',
            },
        ),
        migrations.CreateModel(
            name='UdvUser',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Moderator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='Moderator_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='article',
            name='Status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.StatusType'),
        ),
    ]
