# Generated by Django 2.0.4 on 2018-04-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0002_auto_20180419_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Action',
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Action_Type',
            },
        ),
        migrations.CreateModel(
            name='AlternativeOpinion',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Alternative_opinion',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='BlockOfText',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Block_of_text',
            },
        ),
        migrations.CreateModel(
            name='HierarchyArticles',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Article_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_article', to='server.Article')),
                ('Article_parent_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_article', to='server.Article')),
            ],
            options={
                'db_table': 'Hierarchy_of_articles',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Subtitle', models.CharField(max_length=50)),
                ('Article_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Paragraph',
            },
        ),
        migrations.CreateModel(
            name='PersonBriefInfo',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Person_brief_info',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Source',
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Source_Type',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Status_Type',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Article_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Word', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Term',
            },
        ),
        migrations.CreateModel(
            name='UdvUser',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Moderator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='source',
            name='Source_Type_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.SourceType'),
        ),
        migrations.AddField(
            model_name='blockoftext',
            name='Paragraph_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Paragraph'),
        ),
        migrations.AddField(
            model_name='blockoftext',
            name='Source_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Source'),
        ),
        migrations.AddField(
            model_name='article',
            name='Moderator_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='article',
            name='Status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.StatusType'),
        ),
        migrations.AddField(
            model_name='alternativeopinion',
            name='Block_of_text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.BlockOfText'),
        ),
        migrations.AddField(
            model_name='alternativeopinion',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='Action_Type_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='Block_of_text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.BlockOfText'),
        ),
        migrations.AddField(
            model_name='action',
            name='Moderator_dst_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='moderator_destination', to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='Moderator_src_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='moderator_source', to='server.UdvUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='Status_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.StatusType'),
        ),
    ]
