# Generated by Django 2.0.4 on 2018-04-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180419_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePersonLink',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
                ('Person_brief_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.PersonBriefInfo')),
            ],
            options={
                'db_table': 'Article_Person_link',
            },
        ),
        migrations.CreateModel(
            name='ArticlePhotoLink',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Article_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
                ('Photo_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Photo')),
            ],
            options={
                'db_table': 'Article_Photo_link',
            },
        ),
        migrations.CreateModel(
            name='ArticleTermLink',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Article_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Article')),
                ('Term_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Term')),
            ],
            options={
                'db_table': 'Article_Term_link',
            },
        ),
    ]
