# Generated by Django 2.0.4 on 2018-04-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_articlepersonlink_articlephotolink_articletermlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='Status_Id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Status_id',
        ),
        migrations.AddField(
            model_name='action',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'New'), (3, 'Changes required'), (4, 'Updated')], default=2),
        ),
        migrations.AddField(
            model_name='article',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'New'), (3, 'Changes required')], default=2),
        ),
        migrations.AlterField(
            model_name='action',
            name='Action_Type_Id',
            field=models.IntegerField(choices=[(1, 'Add'), (2, 'Delete'), (3, 'Change')], default=1),
        ),
        migrations.AlterField(
            model_name='source',
            name='Source_Type_Id',
            field=models.IntegerField(choices=[(1, 'Web'), (2, 'TextBook')], default=1),
        ),
        migrations.AlterModelTable(
            name='action',
            table=None,
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AlterModelTable(
            name='source',
            table=None,
        ),
        migrations.DeleteModel(
            name='ActionType',
        ),
        migrations.DeleteModel(
            name='SourceType',
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
    ]
