# Generated by Django 2.0.4 on 2018-04-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180425_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='Action_Type_Id',
            new_name='Action_Type',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='Source_Type_Id',
            new_name='Source_Type',
        ),
    ]
