# Generated by Django 2.0.4 on 2018-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180425_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='Status',
            field=models.CharField(choices=[(1, 'Approved'), (2, 'New'), (3, 'Changes required'), (4, 'Updated')], default=2, max_length=10),
        ),
    ]
